# Generated by Django 3.2.9 on 2021-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=10)),
                ('University', models.CharField(max_length=50)),
                ('Institution', models.CharField(max_length=50)),
                ('PassingYear', models.CharField(max_length=10)),
                ('Percentage', models.CharField(max_length=10)),
            ],
        ),
    ]
