# Generated by Django 3.2.9 on 2021-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_stud_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('mobileNo', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField(max_length=20)),
                ('education', models.CharField(max_length=80)),
                ('docs', models.CharField(max_length=20)),
                ('SrNo', models.IntegerField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('passingYear', models.IntegerField(max_length=20)),
                ('percentage', models.FloatField(max_length=20)),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
