# Generated by Django 3.2.9 on 2021-12-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211207_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='images',
        ),
    ]
