# Generated by Django 3.2.9 on 2021-12-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_stud_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stud',
            new_name='Student',
        ),
    ]
