# Generated by Django 3.2.9 on 2021-12-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_student_stud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stud',
            new_name='Student',
        ),
    ]
