# Generated by Django 3.2.9 on 2021-12-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_stud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
